project_id = "yjiumsnrmgyfamxkpftk"

[functions.decode-vin]
verify_jwt = false

[functions.tesla-auth]
verify_jwt = false

[functions.tesla-api]
verify_jwt = false

[functions.tesla-register-partner]
verify_jwt = false

[functions.send-waiting-for-parts-email]
verify_jwt = false

[functions.notify-customer-arrival]
verify_jwt = false
